services:
  # --- BANCO DE DADOS (Metadata do Airflow) ---
  postgres:
    image: postgres:13
    container_name: dataeng_rag_llm_juridico_postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- ORQUESTRADOR (Airflow) ---
  airflow:
    # image: apache/airflow:2.7.1-python3.10
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: dataeng_rag_llm_juridico_airflow
    container_name: dataeng_rag_llm_juridico_airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=${AIRFLOW_UI_PWD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./data:/opt/bitnami/spark/data
    ports:
      - "8080:8080"
    command: bash -c "airflow db migrate && airflow users create -u admin -p admin -f Admin -l User -r Admin -e admin@example.com || true && touch /opt/airflow/standalone_admin_password.txt && airflow standalone"

  # --- IA LOCAL (Ollama) ---
  ollama:
    image: ollama/ollama:latest
    container_name: dataeng_rag_llm_juridico_ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama

  # --- BANCO VETORIAL (ChromaDB) ---
  chromadb:
    image: chromadb/chroma:latest
    container_name: dataeng_rag_llm_juridico_chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma

  # --- SPARK MASTER ---
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: dataeng_rag_llm_juridico_spark
    container_name: dataeng_rag_llm_juridico_spark_master
    environment:
      - SPARK_MODE=master
    ports:
      - "7077:7077"
      - "8081:8081"
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./scripts:/opt/bitnami/spark/scripts

  # --- SPARK WORKER ---
  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: dataeng_rag_llm_juridico_spark
    container_name: dataeng_rag_llm_juridico_spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./data:/opt/bitnami/spark/data
      - ./scripts:/opt/bitnami/spark/scripts
    depends_on:
      - spark-master

volumes:
  postgres_data: